version: '3'
services:
  postgresdb_test:
    image: postgres:latest
    container_name: postgres_test_container
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST}
    ports:
      - '4567:5432'
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    - pg_data_test:/var/lib/postgresql/data
    networks:
      - learning

volumes:
  pg_data_test:
    # driver: local

# Networks to be created to facilirate communication between containers
networks:
  learning:
    driver: bridge